### PR TITLE
Adding primitives

### PR DESCRIPTION
**Pull request by scoutdb**
- Added style primitives
- Added Box

### CODE REVIEW

**Comment by scoutdb** [comment]
- added new dev dependancy (csstypes)

**Comment by beanpuppy** [comment]
suggestion; there's a lot of `any`s, replace them with the correct type

**Comment by scoutdb** [comment]
> suggestion; there's a lot of `any`s, replace them with the correct type

No props - updated

**Comment by beanpuppy** [comment]
Suggestion; I think it's already shown a little in the storybook example, but you may want to provide a deeper explanation for why to use `Box` and `cs` as opposed to the default `style` in the docstring or something. As in, tell people what it's capable of doing (from reading the code, it's just easier theme access and breakpoints right?)

**Comment by scoutdb** [comment]
> Suggestion; I think it's already shown a little in the storybook example, but you may want to provide a deeper explanation for why to use `Box` and `cs` as opposed to the default `style` in the docstring or something. As in, tell people what it's capable of doing (from reading the code, it's just easier theme access and breakpoints right?)

Yep! - added some small docs

**Review by beanpuppy — APPROVED** [review]
LGTM

**Pull request merged**
