### PR TITLE
feat; Add newsletter modal

### PR DESCRIPTION
**Pull request by symonomicon**
### Newsletter Modal
Changes aim to be a reusable card component for the newsletter implementation.

### Changes 
- Adds newsletter modal
- Adds font-awesome thin `fat` to font awesome library
- Adds styling option to the popover element

### Note
- Not sure what version number to bump into 😬

### CODE REVIEW

**Comment by scoutdb** [comment]
question; can you make this using existing components already?

**Comment by symonomicon** [comment]
Update; 

Moved the entire component to webapp instead; Reused ui components to build in webapp. Still need the icon and popover adjustments for the whole component to work

Moved version to `0.0.100`

**Review by scoutdb — APPROVED** [review]
LGTM

**Comment by beanpuppy** [comment]
> Moved version to `0.0.100`

Did it get uploaded to npm ? @symonomicon

**Comment by scoutdb** [comment]
> > Moved version to `0.0.100`
> 
> Did it get uploaded to npm ? @symonomicon

npm publish wont bump it if you already have

**Pull request merged**
